BEGIN;

DROP TABLE IF EXISTS "user", "post", "shortcut", "post_tag", "comment";

CREATE TABLE "user" (
    "id" SERIAL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" VARCHAR(100) UNIQUE NOT NULL,
    "email" VARCHAR(255) UNIQUE NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "profile_picture" TEXT,
    "role" ENUM('user', 'admin') DEFAULT 'user',
    "bio" TEXT,
    "is_active" BOOLEAN DEFAULT TRUE,
    "is_deleted" BOOLEAN DEFAULT FALSE,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "post" (
    "id" SERIAL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" VARCHAR(100) NOT NULL,
    "content" TEXT NOT NULL,
    "published" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "edited" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "category" VARCHAR(100),
    "source_url" TEXT,
    "thumbnail" VARCHAR(2048),
    "status" ENUM('draft', 'published', 'deleted') DEFAULT 'draft',
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE "tag" (
    "id" SERIAL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tag_name" VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE "post_tag" (
    "post_id" INTEGER NOT NULL,
    "tag_id" INTEGER NOT NULL,
    PRIMARY KEY ("post_id", "tag_id"),
    FOREIGN KEY ("post_id") REFERENCES "post" ("id") ON DELETE CASCADE,
    FOREIGN KEY ("tag_id") REFERENCES "tag" ("id") ON DELETE CASCADE
); 

CREATE TABLE "comment" (
    "id" SERIAL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "message" TEXT NOT NULL,
    "post_id" INTEGER NOT NULL,
    "user_id" INTEGER NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("post_id") REFERENCES "post" ("id") ON DELETE CASCADE,
    FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE
);

CREATE TABLE "shortcut" (
    "id" SERIAL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(100) NOT NULL,
    "url" TEXT NOT NULL,
    "icon_url" TEXT,
    "order_index" INTEGER DEFAULT 0,
    "user_id" INTEGER NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE
);

CREATE TABLE "LIKE_POST" (
    "post_id" INTEGER NOT NULL,
    "user_id" INTEGER NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_like UNIQUE ("post_id", "user_id")
    FOREIGN KEY ("post_id") REFERENCES "post" ("id") ON DELETE CASCADE,
    FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE
);

COMMIT;